# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
      with:
        args: test
        
    - name: Upload Test HTML Result
      if: failure() || success()
      uses: actions/upload-artifact@v1
      with:
        name: test-result
        path: build/reports/tests/test
